[project]
name = "py03-benchmark"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Rust",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
]
dynamic = ["version"]
dependencies = [
    "asyncio>=4.0.0",
    "numpy>=1.24.4",
    "plotly>=6.4.0",
    "ruff>=0.14.5",
    "scylla_python_serialization @ git+https://github.com/jakub-graczyk/python-rs-driver@benchmarks-python-typed",
    "scylla_rust_python_serialization @ git+https://github.com/patrycja-ziemkiewicz/python-rs-driver@benchmark",
    "scylla_rust_serialization @ git+https://github.com/paulinaczajkowska/python-rs-driver@benchmark"


]

[build-system]
requires = ["maturin>=1.7,<2.0"]
build-backend = "maturin"

[tool.maturin]
python-source = "python"
features = ["pyo3/extension-module"]
module-name = "py03_benchmark.py03_benchmark"

[dependency-groups]
dev = ["pytest", "pytest-asyncio","maturin"]

[tool.uv]
cache-keys = [
    { file = "pyproject.toml" },
    { file = "Cargo.toml" },
    { file = "src/*.rs" },
    { file = "python/*.py"},
    { file = "python/*.pyi"},
]
config-settings = { build-args = '--profile=dev' }
